# Generated by Django 3.1.7 on 2021-03-24 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suggestion',
            old_name='question',
            new_name='suggestion',
        ),
    ]
