# Generated by Django 3.1.7 on 2021-03-24 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20210324_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='subject',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
