# Generated by Django 3.1.7 on 2021-03-25 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_suggestion_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestion',
            name='subject',
        ),
    ]
