# Generated by Django 3.1.7 on 2021-04-01 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_auto_20210401_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='presenting',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
